apiVersion: v1
kind: Service
metadata:
  annotations:
    serviceloadbalancer/lb.cookie-sticky-session: "true"
    serviceloadbalancer/lb.host: launcher-1.playground.preprod.ballerina.io
    serviceloadbalancer/lb.sslTerm: "true"
    # serviceloadbalancer/lb.routePath: "/api/run"
  labels:
    app: bpg-launcher
  name: bpg-launcher
  namespace: ballerina-playground
spec:
  ports:
    # - name: "web-port-http"
    #   port: 80
    #   targetPort: 80
    - name: "web-port-https"
      port: 443
      targetPort: 443  
  selector:
    app: bpg-launcher-1

