apiVersion: v1 
kind: Service 
metadata: 
  annotations: 
    serviceloadbalancer/lb.cookie-sticky-session: "true" 
    serviceloadbalancer/lb.host: controller.playground.preprod.ballerina.io
    serviceloadbalancer/lb.sslTerm: "true"
  labels:
    app: bpg-controller 
  name: bpg-controller 
  namespace: ballerina-playground 
spec: 
  ports:
  -
    name: "web-port-https"
    port: 443
    targetPort: 8443
  selector: 
    app: bpg-controller 
 