apiVersion: v1
kind: Service
metadata:
  annotations:
     serviceloadbalancer/lb.private: "true"
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
