site_name: Ballerina Documentation
repo_url: https://github.com/ballerinalang/ballerina
site_description: Documentation for the Ballerina Programming Language
site_author: WSO2, Inc.
copyright: 2018 WSO2, Inc.
theme: null
theme_dir: three-column-pages
plugins: []
