site_name: Ballerina.io
repo_url: https://github.com/ballerina-guides/
site_description: Guides for the Ballerina Programming Language
site_author: WSO2, Inc.
docs_dir: repos
edit_uri: /edit/master/README.md
copyright: 2018 WSO2, Inc.
theme: null
theme_dir: ballerina.io-guide-theme
plugins: []