name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # This will download new version of api-docs and make a pull request to ballerina-dev-website
    - name : Update Api-docs
      env:
        GITHUB_TOKEN: ${{secrets.WEBSITE_TOKEN}} 
        NEW_VERSION: 1.2.0
      run: |

        wget https://product-dist.ballerina.io/downloads/$NEW_VERSION/ballerina-$NEW_VERSION.zip
        sudo apt-get install unzip
        unzip ballerina-$NEW_VERSION.zip
        
        git config --global user.email "rdulmina@gmail.com"
        git config --global user.name "rdulmina"
        
        git clone https://rdulmina:$GITHUB_TOKEN@github.com/rdulmina/ballerina-dev-website.git
        
        cd ballerina-dev-website
        git checkout automate-api-docs-update
        git pull origin master
        
        mkdir -p v1-2/learn/api-docs
        cp -avr ../ballerina-1.2.0/distributions/jballerina-1.2.0/lib/repo/ballerina/ v1-2/learn/api-docs

