name: Scheduled Ballerina Central Tests on Dev 

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Docker
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Run Script
      working-directory: ./test-scripts/ballerina-central/
      run: docker build --build-arg BALLERINA_CENTRAL_ACCESS_TOKEN=${{ secrets.BALLERINA_DEV_CENTRAL_ACCESS_TOKEN }} --build-arg BALLERINA_DEV_CENTRAL=true .
