name: Java CI

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: ./test-scripts/ballerina-test-automation
      run: ./gradlew build --stacktrace -scan --console=plain --no-daemon
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: ./test-scripts/ballerina-test-automation
      run: |
        wget https://product-dist.ballerina.io/downloads/1.1.2/ballerina-windows-installer-x64-1.1.2.msi
        msi.exe /i ballerina-windows-installer-x64-1.1.2.msi /qn /l "install-log.log"
        ballerina -v
        ./gradlew.bat build --stacktrace -scan --console=plain --no-daemon
  # macos-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up JDK 1.8
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: 1.8
  #   - name: Build with Gradle
  #     working-directory: ./test-scripts/ballerina-test-automation
  #     run: ./gradlew build --stacktrace -scan --console=plain --no-daemon
  # centos-build:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: centos:7
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up JDK 1.8
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: 1.8
  #   - name: Build with Gradle
  #     env:
  #       OS_TYPE: centos
  #     working-directory: ./test-scripts/ballerina-test-automation
  #     run: ./gradlew build --stacktrace -scan --console=plain --no-daemon
