name: Build and Publish Intellij Plugin
on:
  push:
  
jobs:
  trigger_workflow:
     strategy:
       matrix:
         os: [ubuntu-latest]
     runs-on: ${{ matrix.os }}
     env:
         working-directory: ./tools-plugin/intellij
         publish_token: ${{ secrets.PUBLISH_TOKEN }}
     steps:
       - uses: actions/setup-java@v1
         with:
           java-version: 1.8
       - uses: actions/checkout@v2
         with:
           repository: lasinicl/myPluginRepo2
           ref: dummyBranch 
       - name: build and publish plugin
         working-directory: ${{env.working-directory}}
         run: |
              ./gradlew buildPlugin 
              ./gradlew publishPlugin -PintellijPublishToken=${{ env.publish_token }}
       
