name: Run Gradle on PR
on: 
  push:
  repository_dispatch:
    
jobs:
  trigger_workflow:
     strategy:
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
     runs-on: ${{ matrix.os }}
     env:
         MY_PAT: ${{ secrets.MY_PAT }}
     steps:
       -name: create repository dispatch event
       if: env.REPOSITORY_DISPATCH=='true'
       shell: pwsh
       run: |
          $pat = $env:MY_PAT
          $uri = "https://github.com/lasinicl/myPluginRepo/dispatches"
          $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "", $pat)))
          $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
          $headers.Add("Content-Type", "application/json")
          $body = "{`"event_type`":`"test`",`"client_payload`":{`"unit`":false,`"integration`":true}}"
          $response = Invoke-RestMethod -Uri $uri -Headers $headers -Body $body -Method POST
          $response | ConvertTo-Json
          

