name: Run Gradle on PR
on: 
  push:
  repository_dispatch:
    
jobs:
  trigger_workflow:
     strategy:
       matrix:
         os: [ubuntu-latest, macos-latest]
     runs-on: ${{ matrix.os }}
     steps:
       - name: dispatch intitation
         run: |
           curl -X POST https://api.github.com/repos/lasinicl/myPluginRepo/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -u ${{ secrets.MY_PAT }} --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
          

