name: Run Gradle on PR
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/checkout@v2
      with: 
        repository: lasinicl/myPluginRepo
        - uses: eskatos/gradle-command-action@v1
          with:
             build-root-directory: /tools-plugin/intellij
             arguments: buildPlugin
        - uses: eskatos/gradle-command-action@v1
          with:
             build-root-directory: /tools-plugin/intellij
             arguments: publishPlugin
