name: Run Gradle on PR1
on: 
  push: 
jobs:
  trigger_workflow:
     strategy:
       matrix:
         os: [ubuntu-latest]
     runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/setup-java@v1
         with:
           java-version: 1.8
       - name: use plugin repo
       - uses: actions/checkout@v2
         with:
           repository:lasinicl/myPluginRepo2
         working-directory: tools-plugin/intellij
         run: ./gradlew buildPlugin
         run: ./gradlew publishPlugin
