name: Update Standard Library Dependency Graph

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  create:
    name: Update Standard Library Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python Packages
        run: |
          pip install graphviz
          pip install requests
          sudo apt-get install graphviz
          pip install retry
          pip install PyGithub

      - name: Get Dependencies and Update Dependency Graph
        run: |
          python dependabot/update_stdlib_dependency_graph.py
      - name: Commit Files
        run: |
          git config --local user.email ${{ secrets.BALLERINA_BOT_EMAIL }}
          git config --local user.name ${{ secrets.BALLERINA_BOT_USERNAME }}
          git add -A
          git commit -m "Update stdlib dependency graph" -a

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BALLERINA_BOT_TOKEN }}
          branch: master
