name: Update download page of the ballerina.io

# Controls when the action will run. Triggers the workflow on release
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  Update:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.WEBSITE_TOKEN}}
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
   
    - name: Cloning ballerina-dev-website
      run: git clone https://rdulmina:$GITHUB_TOKEN@github.com/rdulmina/ballerina-dev-website.git
    # For now we have hard coded the latest version number  
    - name: Updating downloads.html
      env:
        latest_version: 1.2
      run: |

        cd ballerina-dev-website
        git checkout automate-downloads-page-update 2>/dev/null || git checkout -b automate-downloads-page-update
        git pull origin master
        python3 ../publish_scripts/update-downloads-page.py $latest_version
        
        git config --global user.email "rdulmina@gmail.com"
        git config --global user.name "rdulmina"
        git add .
        git commit --allow-empty -m 'downloads page update'
        
        git push --set-upstream origin automate-downloads-page-update
        echo 'Successfully pushed to automate-downloads-page-update branch'

        sudo snap install hub --classic
        hub pull-request -m 'This is an automated pull request to update downloads page for new release'
        echo 'Successfully sent a pull request to ballerina-platform/ballerina-dev-website'

      

