name: Update download page of the ballerina.io

# Controls when the action will run. Triggers the workflow on release
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  Update:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
   
    - name: Downloading downloads.html
      run: svn export --force https://github.com/ballerina-platform/ballerina-dev-website/trunk/downloads.html
    # For now we have hard coded the latest version number  
    - name: Obtaining the latest version of ballerina
      env:
        latest_vesion: 1.2
      
    - name: Updating downloads.html
      run: echo $latest_vesion
