name: Update Dependency Graph

on:
  workflow_dispatch:
  schedule:
    - cron: 0 00 17 * *

jobs:
  dependency:
    name: Derive module dependencies
    runs-on: ubuntu-latest
    steps:
      -   name : Configure GitHub
          env:
            GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
          run: |
            git config --global user.name ${{ secrets.BALLERINA_BOT_USERNAME }}
            git config --global user.email ${{ secrets.BALLERINA_BOT_EMAIL }}
            git clone https://${{ secrets.BALLERINA_BOT_USERNAME }}:${{ secrets.BALLERINA_BOT_TOKEN }}@github.com/ballerina-platform/ballerina-release.git
            cd ballerina-release

      -   name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

      -   name: Install Python packages
          run: |
            pip install requests
            pip install networkx
            pip install retry
            pip install PyGithub
            pip install semver

      -   name: Get Dependencies and update files
          run: |
            cd ballerina-release
            python dependabot/update_version_data.py
          env:
            packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
            packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}

      -   name : Commit files
          id: commit
          env:
            GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
          run: |
            cd ballerina-release
            git update-index -q --refresh
            if ! git diff-index --quiet HEAD --;then
                echo ::set-output name=changes::true
                git remote set-url origin https://${{ secrets.BALLERINA_BOT_USERNAME }}:${{ secrets.BALLERINA_BOT_TOKEN }}@github.com/ballerina-platform/ballerina-release.git
                git add .
                git commit -m "[Automated] Update the dependency order"
                curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
                bin/hub push origin main
            else
                echo "No changes to commit"
            fi
